steps:
# Decrypt the android signing keystore and properties
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=android/keystore.properties.enc
  - --plaintext-file=android/keystore.properties
  - --location=global
  - --keyring=github-keyring
  - --key=android-key

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=android/key.jks.enc
  - --plaintext-file=android/key.jks
  - --location=global
  - --keyring=github-keyring
  - --key=android-key

# Make a release build of the APK
- name: 'gcr.io/$PROJECT_ID/flutter'
  args: ['build', 'apk']

# Ship the built APK to a cloud storage bucket
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'build/app/outputs/apk/release/app-release.apk', 'gs://scc-build-output/scc_companion_app_$BUILD_ID.apk']
